stages:
  - build
  - lint
  - test
  - publish

before_script:
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1
  - export DOTNET_PRINT_TELEMETRY_MESSAGE=false
  - export ASPNETCORE_ENVIRONMENT=Production
  - export ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
  - export PATH=$PATH:$HOME/.dotnet/tools
  - dotnet --info
  - dotnet tool install JetBrains.ReSharper.GlobalTools --global || echo "JB already installed."

build:
  stage: build
  script:
    - dotnet restore --configfile nuget.config
    - dotnet build --no-self-contained

lint:
  stage: lint
  script:
    - jb inspectcode ./*.sln --output=analyze_output.xml --build
    - grep -q 'WARNING' analyze_output.xml && echo "Warning found" && cat analyze_output.xml && exit 1 || echo "No warning found"
  artifacts:
    when: always
    expire_in: 1 day
    paths:
      - ./analyze_output.xml

test:
  stage: test
  script:
    - dotnet test *.sln --collect:"XPlat Code Coverage" --logger "junit;MethodFormat=Class"
  artifacts:
    when: always
    expire_in: 1 day
    paths:
      - ./**/TestResults.xml
      - ./**/coverage.cobertura.xml
    reports:
      junit:
        - ./**/TestResults.xml
      coverage_report:
        coverage_format: cobertura
        path: ./**/coverage.cobertura.xml

publish:
  stage: publish
  script:
    - dotnet publish --configuration Release --runtime linux-x64 --no-self-contained *.sln
    - dotnet pack --configuration Release *.sln || echo "Some packaging failed!"
  artifacts:
    paths:
      - '**/*.nupkg'
