stages:
  - restore
  - build
  - analyze
  - test
  - publish
  - pack

before_script:
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1
  - export DOTNET_PRINT_TELEMETRY_MESSAGE=false
  - export ASPNETCORE_ENVIRONMENT=Production
  - export ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
  - export PATH=$PATH:$HOME/.dotnet/tools
  - dotnet tool install JetBrains.ReSharper.GlobalTools --global || echo "JB already installed."

restore:
  stage: restore
  script:
    - dotnet restore --configfile nuget.config

build:
  stage: build
  script:
    - dotnet build --no-self-contained

analyze:
  stage: analyze
  script:
    - jb inspectcode ./Aiursoft.NugetNinja.sln --output=analyze_output.xml --build
  artifacts:
    paths:
      - analyze_output.xml

test:
  stage: test
  script:
    - dotnet test *.sln --collect:"XPlat Code Coverage" -r cobertura
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cobertura/*/coverage.cobertura.xml

publish:
  stage: publish
  script:
    - dotnet publish --configuration Release --runtime linux-x64 --no-self-contained *.sln

pack:
  stage: pack
  script:
    - dotnet pack --configuration Release *.sln || echo "Some packaging failed!"
  artifacts:
    paths:
      - '**/*.nupkg'