stages:
  - restore
  - build
  - analyze
  - test
  - publish
  - pack

before_script:
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1

restore:
  stage: restore
  script:
    - dotnet restore --configfile nuget.config

build:
  stage: build
  script:
    - dotnet build --configuration Release --runtime win-x64 --no-self-contained

analyze:
  stage: analyze
  script:
    - dotnet tool install JetBrains.ReSharper.GlobalTools --global
    - dotnet resharper-cleanupcode Aiursoft.NugetNinja.sln

test:
  stage: test
  script:
    - dotnet test --collect "Code coverage"

publish:
  stage: publish
  script:
    - dotnet publish --configuration Release --output --runtime linux-x64 --no-self-contained --projects '**/*.csproj'

pack:
  stage: pack
  script:
    - dotnet pack --configuration Release --project src/NugetNinja/NugetNinja.csproj

